title: "Karlz"
author: "Karl Zhang"
description: "Code, Climbing, Cook"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "index.md"}
  - {title: "posts", file: "posts.md"}
  - {title: "中文 Blog", file: "README.md"}
  - {title: "Resume", url: "https://karlz97.github.io/YindingZhang_Resume_20221005.pdf"}
  - {title: "Resume2", url: "/YindingZhang_Resume_20221005.pdf"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:yindingzhang@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/karlz97"}
  - {title: twitter, icon: twitter, url: "https://twitter.com/yapiy4"}
  - {title: weixin, icon: weixin, url: "/wechat.png"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
